# Generated by Django 2.2.16 on 2022-07-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
