# Generated by Django 2.2.16 on 2022-07-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20220707_0032"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.TextField(max_length=150),
        ),
    ]
